### ISSUE TITLE
Sympy computation limit

### ISSUE THREAD

**Issue by rredelmeier** [bbolker/math3mb#17]
Hi Dr. Bolker,

Quick question about sympy, which is sufficiently unrelated to the course it's definitely alright if you can't get to it. In terms of getting it to solve pretty big systems of nonlinear equations, it obviously takes a while. Does it work that if we give it enough time, it will wind up with a solution? Or is there an upper limit on how much it can do for us, and giving it an hour or 10 hours wont matter?

**Comment by bbolker** [comment]
In theory there's no upper limit, but in practice I would say that if you don't have an answer after an hour, you probably won't be able to get an answer within any practical amount of time.   

Also, if you get an answer after many hours of computation, it may be too complicated to be very useful.
