### ISSUE TITLE
Tim Hortons Model

### ISSUE THREAD

**Issue by wang988** [bbolker/math3mb#3]
I have a question about the Tim Hortons Model. N(0)= 87, the rate is +3 per year. Why is it a decreasing function?

**Comment by bbolker** [comment]
The rate of *addition of new stores* is 3 per year.  However, only 90% of existing stores/survive 10% of existing stores are lost every year (the formula is N(t+1)=3+0.9*N(t)).  If we start with more than the equilibrium level (a/(1-b) = 3/(1-0.9) = 30), then more old stores are being lost each year than new ones added.  For example, suppose we start with 90 stores.  10%, or 9, are lost, 3 are added, for a net loss of 6.

Does that make sense?

**Comment by wang988** [comment]
Oh thanks I see! I remember the assumption was lifetime=10 years. Now I understand Thank you!
